### ISSUE TITLE
交易被转移走

### ISSUE THREAD

**Issue by chenlerry** [AITTCOIN/AITTCOIN#3]
<img width="556" alt="image" src="https://github.com/user-attachments/assets/d321a169-794c-4a80-963c-1447824945cc">

当前节点运行在本地windows下面，且交易是在夜间被转走，当时节点都没有启动，同时节点钱包有设置密码，这个是什么情况，windows程序有bug？

**Comment by AITTCOIN** [comment]
A few days ago, a project called Regus was found to have built-in malware. The regus client would scan all wallet.dat files on the user's computer and upload them to the attacker's server. The attacker would rob the user's wallet and sell it on xeggex. 
This was reported by multiple users in the community. We cannot know the details of the attack because Regus deleted all their git repositories and websites. 
But we can be sure that AITT is safe. This is the scan record of the latest AITTCOIN client: 

https://www.virustotal.com/gui/file/c8704f5b8824691fa23d9b27d82291f4da134ef54802596497a2b2bb33f8d430/detection

**Comment by AITTCOIN** [comment]
If you or someone in your organization has downloaded Regus, please completely remove it and run anti-virus software. It may turn your computer or your organization's computer into a bot and continue to steal your crypto.
